---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.8
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]

suites:
  - name: package
    run_list:
      - recipe[elixir::default]
    attributes:
      elixir:
        install_method: "package"
  - name: source
    run_list:
      - recipe[elixir::default]
    attributes:
      elixir:
        install_method: "source"
