driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: fedora-26
  - name: opensuse-leap-42
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]

suites:
  - name: package
    run_list:
      - recipe[elixir::default]
    attributes:
      elixir:
        install_method: "package"
  - name: source
    run_list:
      - recipe[elixir::default]
    attributes:
      elixir:
        install_method: "source"
